package com.example.messenger.Authentication;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.util.Patterns;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.Toast;

import com.example.messenger.HomePage;
import com.example.messenger.R;
import com.example.messenger.UserData.User;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

public class RegistrationPage extends AppCompatActivity {

    EditText RName,RPhone,REmail,RPassword;
    Button RRegBtn;
    ProgressBar RProgress;
    ImageView RProfile;

    String userId;

    private FirebaseAuth mAuth; //For Firebase Authentication
    private DatabaseReference mDatabase;    //For Real time Database

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_registration_page);
        this.bindCOmponents();
        //For Register Button Action
        RRegBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                registerUser();
            }
        });


    }
//********************
    private void bindCOmponents()
    {
        RName = findViewById(R.id.RName);
        RPhone=findViewById(R.id.RPhone);
        REmail=findViewById(R.id.REmail);
        RPassword=findViewById(R.id.RPassword);
        RProgress=findViewById(R.id.RProgressBar);
        RRegBtn = findViewById(R.id.RRegBtn);
        RProfile=findViewById(R.id.RimageView);
    }

 //**************************************
 private void registerUser() {
     if (validateUserDetails()) {
         String name = RName.getText().toString().trim();
         String phone = RPhone.getText().toString().trim();
         String email = REmail.getText().toString().trim();
         String password = RPassword.getText().toString().trim();


         //need to get Firebase Authentication instance
         mAuth = FirebaseAuth.getInstance();

         //Default method provided by Firebase by their tutorial
         mAuth.createUserWithEmailAndPassword(email, password)
                 .addOnCompleteListener(this, new OnCompleteListener<AuthResult>() {
                     @Override
                     public void onComplete(@NonNull Task<AuthResult> task) {
                         if (task.isSuccessful()) {

                             //to upload Profile Image on server
                             //   UploadImage();

                             //User Account Created in Firebase Authentication
                             //----------------------------------
                             //need to to Input Data to Realtime Databse using FirebaseDatabase object
                             mDatabase = FirebaseDatabase.getInstance().getReference();

                             //to get current users uid(unique id generated by authentication)
                             String UserId = mAuth.getCurrentUser().getUid();


                             //Create java Class user to store input data at once object
                             User user = new User(UserId, name, phone, email);

                             //store user data in Realtimetime Database in child-user format

                             mDatabase.child("users").child(UserId).setValue(user);


                             //Remaining tasks
                             // --------------------------------
                             Toast.makeText(RegistrationPage.this, "User Registration Done", Toast.LENGTH_LONG).show();
                             Intent i = new Intent(RegistrationPage.this, HomePage.class);
                             startActivity(i);
                             //
                         } else {
                             Toast.makeText(RegistrationPage.this, "User Registration Failed", Toast.LENGTH_LONG).show();
                         }
                     }
                 });
     }
  }

 //************************************
     private boolean validateUserDetails()
     {
         String email=REmail.getText().toString().trim();
         String password=RPassword.getText().toString().trim();
         String fullName=RName.getText().toString().trim();
         String phone =RPhone.getText().toString().trim();

         if(fullName.isEmpty())
         {
             RName.setError("Full Name is Required");
             RName.requestFocus();
             return false;
         }

         if(phone.isEmpty())
         {
             RPhone.setError("Phono  no is Required");
             RPhone.requestFocus();
             return false;
         }
         if(phone.length()!=10)
         {
             RPhone.setError("Enter correct Format");
             RPhone.requestFocus();
             return false;
         }
         if(email.isEmpty())
         {
             REmail.setError("Email is Required");
             REmail.requestFocus();
             return false;
         }
         if(!Patterns.EMAIL_ADDRESS.matcher(email).matches())
         {
             REmail.setError("Please provide Valid Email");
             REmail.requestFocus();
             return false;
         }
         if(password.isEmpty())
         {
             RPassword.setError("Password is Required");
             RPassword.requestFocus();
             return false;
         }
         if(password.length() < 8)
         {
             RPassword.setError("Password should At least 6 length");
             RPassword.requestFocus();
             return false;
         }
         return  true;
     }
 //******************************************************


}